# 异常处理

C++程序中出现异常时,检测到异常的程序段可以通过抛出(throw)异常来通知"异常已经发生"

`throw`表达式与`return`相似

`try`块把处理代码(catch语句)和一组程序语句关联起来

异常规范:提供了一种方案,随着函数声明列出该函数可能抛出的异常